// document.writeln("<!--裝置說明 & 企業介紹-->");
// document.writeln("    <section class=\'info\'>");
// document.writeln("      <div class=\'inner-wrapper\'>");
// document.writeln("        <img class=\'game-icon\' src=\'images/icon.png\' alt=\'塞爾之光\'>");
// document.writeln("        <table class=\'game-info\'>");
// document.writeln("          <tr>");
// document.writeln("            <td>相容配備 &nbsp; | </td>");
// document.writeln("            <td>智慧型手機或平板電腦<br>IOS手機-iPhone 6S以上機型<br>Android-CPU:1.2Ghz，內存2GB以上機型</td>");
// document.writeln("          </tr>");
// document.writeln("          <tr>");
// document.writeln("            <td>作業系統 &nbsp; | </td>");
// document.writeln("            <td>Android 5以上 / IOS 8.0以上</td>");
// document.writeln("          </tr>");
// document.writeln("          <tr>");
// document.writeln("            <td>網路連線 &nbsp; | </td>");
// document.writeln("            <td>4G / Wifi，建議開啟Wifi連線可獲得遊戲最佳體驗狀態</td>");
// document.writeln("          </tr>");
// document.writeln("        </table>");
// document.writeln("      </div>");
// document.writeln("      <ul>");
// document.writeln("        <li>");
// document.writeln("          <a href=\'http://www.ican.com.tw/index_home.html\' target=\'_blank\'>關於我們</a>");
// document.writeln("        </li>");
// document.writeln("        <li>");
// document.writeln("          <a href=\'http://www.icantw.com/services\' target=\'_blank\'>服務條款</a>");
// document.writeln("        </li>");
// document.writeln("        <li>");
// document.writeln("          <a href=\'http://www.icantw.com/cooperate\' target=\'_blank\'>異業合作</a>");
// document.writeln("        </li>");
// document.writeln("        <li>");
// document.writeln("          <a href=\'https://www.104.com.tw/jobbank/custjob/index.php?r=cust&j=453f4770393b436c35373f683d433b1e12e2e2e2c463b4f2634j53&jobsource=n104bank1\' target=\'_blank\'>艾肯徵才</a>");
// document.writeln("        </li>");
// document.writeln("      </ul>");
// document.writeln("    </section>  ");
// document.writeln("  </div>");
document.writeln("<!--copyright-->");
document.writeln("  <footer>");
document.writeln("    <div class=\'footer-outer\'>");
document.writeln("      <div class=\'footer-left\'>");
document.writeln("        <div class=\'ican-logo\'>");
document.writeln("          <img src=\'images/ican.png\' alt=\'艾肯娛樂\'>");
document.writeln("        </div>");
document.writeln("        <div class=\'all-right\'>©<span>iCan</span>Entertainment Co.,Ltd. All Rights Reserved.</div>");
document.writeln("      </div>");
document.writeln("      <div class=\'logos\'>");
document.writeln("        <img src=\'images/logos.png\' alt=\'享樂時光\'>");
document.writeln("      </div>");
document.writeln("      <div class=\'footer-right\'>");
document.writeln("        <div class=\'classLevel\'>");
document.writeln("          <img src=\'images/15+.jpg\' alt=\'15+\'>");
document.writeln("        </div>");
document.writeln("        <div class=\'classTxt\'>");
document.writeln("              ◆ 本遊戲涉及輕微性暗示、不當言語及暴力，角色穿著突顯胸、臀之服飾。");
document.writeln("          <br>◆ 注意使用時間，請避免沉迷遊戲。");
document.writeln("          <br>◆ 遊戲部分內容需另外支付費用。");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </footer>");